apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: node-redis
  template:
    metadata:
      labels:
        app: node-redis
    spec:
      containers:
        - name: node-redis
          image: arthurescriou/node-redis:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '5000'
            - name: REDIS_URL
              value: 'redis://redis-service:6379'
